dist:
  trusty

language:
  cpp

compiler:
  gcc

env:
  global:
    - COVDIR=coverage
    - LIBSEMI=v0.6.0
    - g++=g++-5
    - gcc=gcc-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5-multilib
      - libtool

# Matrix
#                    | GAP: master  | GAP: stable-4.9 | GAP: required |
#--------------------+--------------+-----------------+---------------+
# packages:   master | 64- & 32-bit |               - |             - |
# packages:   newest |       64-bit |               - |             - |
# packages: required |   (coverage) |               - |             - |

# Plus: linting, and code coverage

matrix:
  include:
    - env:
      - SUITE=lint
      addons:
        apt_packages:
      sudo:
        false

    - env:
      - SUITE=test
      - GAP=master
      - PACKAGES=master
      - ABI=64
      sudo:
        required

    - env:
      - SUITE=test
      - GAP=master
      - PACKAGES=master
      - ABI=32
      sudo:
        required

    - env:
      - SUITE=test
      - GAP=master
      - PACKAGES=newest
      - ABI=64
      sudo:
        required

    - env:
      - SUITE=coverage
      - GAP=master
      - PACKAGES=required
      - ABI=64
      - THRESHOLD=95
      sudo:
        required

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$ABI" == "32" ]; then
      export GAP_FLAGS="ABI=32 --host=i686-linux-gnu";
      export PKG_FLAGS="CFLAGS=-m32 CXXFLAGS=-m32 LDFLAGS=-m32 LOPTS=-m32 --host=i686-linux-gnu";
    fi;

before_script:
  - export GAPROOT="$HOME/gap"
  - if [ "$SUITE" != "lint" ]; then
      echo "deb http://www.mirrorservice.org/sites/archive.ubuntu.com/ubuntu/ zesty main" | sudo tee -a /etc/apt/sources.list;
      sudo apt-get update -qq;
      sudo apt-get install --only-upgrade autoconf;
    fi;
  - if [ "$ABI" == "64" ]; then sudo apt-get install libgmp-dev; fi;
  - if [ "$ABI" == "32" ]; then
      sudo apt-get install libgmp-dev:i386;
      sudo ln -s /usr/include/asm-generic /usr/include/asm;
    fi;
  - scripts/travis-build-dependencies.sh

script:
  - scripts/travis-build-semigroups.sh && scripts/travis-test.sh
